version: "3"
services:
  app:
    build: ./python_script/
    container_name: 'python'
    volumes:
      - ./python_script/dummy_data.py:/home/dummy_data.py
      - ./python_script/script.sh:/home/script.sh
    networks:
      - poc-benthos
  # Broker
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   depends_on:
  #     - mysql
  #   networks:
  #     - poc-benthos
  # CDC or ETL data engineer tool
  benthos:
    image: jeffail/benthos
    container_name: 'benthos'
    volumes:
      - ./benthos_config/benthos.yml:/benthos.yml
    ports:
      - 4195:4195
      - 4190:4190
    depends_on:
      - postgres
      - mysql
      - app
    networks:
      - poc-benthos 
  # Data source, for benthos.
  mysql:
    image: mysql:5.7
    restart: always
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    volumes:
      - ./sql_script:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - poc-benthos
  postgres:
    image: postgres
    restart: always
    container_name: 'postgres'
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
    networks:
      - poc-benthos 
networks:
  poc-benthos:
    driver: bridge